name: ToXiiCxPickup
main: net.toxiic.drops.Drops
version: 1.0.0
api-version: 1.13
authors: [ToXiiC]
description: Automatic drops and smelt.
depend: [WorldGuard]
softdepend: [HolographicDisplays]
commands:
  autopickup:
    description: Drops Command.
  autosmelt:
    description: AutoSmelt Command.
  toxiicpickup:
    description: Admin Commands.	